/* ============================================
   SITE CONFIG — auto-generated by installer
   For local dev: set API_BASE to http://localhost:5000/api
   For production: installer sets this to /api (nginx proxy)
   ============================================ */
const API_BASE = window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1'
    ? 'http://localhost:5000/api'
    : '/api';
